### ISSUE TITLE
Error when not specifying dedicated keys in metadatas

### ISSUE THREAD

**Issue by allamand** [aws-samples/eks-blueprints-add-ons#161]
I've not put some metadatas to configure external-dns or ingress-nginx then I got some errors:

```
failed to execute go template controller: service: type: {{default "LoadBalancer" .metadata.annotations.ingress_nginx_service_type}} : template: :3:44: executing "" at <.metadata.annotations.ingress_nginx_service_type>: map has no entry for key "ingress_nginx_service_type"
```

With configurations like :

```
values: |
              controller:
                service:
                  type: {{default "LoadBalancer" .metadata.annotations.ingress_nginx_service_type}}
```

I would like the GoTemplate to select the default value without throwing an error.
