### ISSUE TITLE
[Bug] `chart/templates/tetrate-istio.yaml` should use `spec: ignoreDifferences:` to hide things that will always be out of sync

### ISSUE THREAD

**Issue by spkane** [aws-samples/eks-blueprints-add-ons#37]
There are some fields that will ALWAYS show a difference in ArgoCD unless `ignoreDifferences` is set correctly in the `Application` manifest for `tetrate-istio`

![CleanShot 2022-05-06 at 12 51 01](https://user-images.githubusercontent.com/129629/167207657-bc6752b2-c404-4095-ac17-37c29792a59c.png)

See:  https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#application-level-configuration

I'll add the exact config here, if/when I work it out.

**Comment by spkane** [comment]
I feel like something like this **should** work, and although I can get this to apply and not produce any errors, it also does not hide the diff.

```
  ignoreDifferences:
  - kind: MutatingWebhookConfiguration
    name: istio-sidecar-injector
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - kind: ValidatingWebhookConfiguration
    name: istiod-default-validator
    jqPathExpressions:
    - '.webhooks[]?.failurePolicy'
```

 Mode docs: https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/diffing.md#application-level-configuration

**Comment by spkane** [comment]
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: istiod-default-validator
```

![CleanShot 2022-05-06 at 14 12 27](https://user-images.githubusercontent.com/129629/167217227-7da55edd-7bfa-44d1-a9da-9580d83467e7.png)

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
```

![CleanShot 2022-05-06 at 14 19 10](https://user-images.githubusercontent.com/129629/167217894-6353eddf-518f-4efc-a43f-8a688b9e298c.png)

**Comment by spkane** [comment]
I think that this is indeed the correct thing to add to the Application spec:

```yaml
  ignoreDifferences:
  - kind: MutatingWebhookConfiguration
    name: istio-sidecar-injector
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - kind: ValidatingWebhookConfiguration
    name: istiod-default-validator
    jqPathExpressions:
    - '.webhooks[]?.failurePolicy'
```

But I have reported a bug upstream, as I can't actually get this to work, despite what the documentation suggests.

**Comment by allamand** [comment]
@spkane, what is the status on this one ?

**Comment by spkane** [comment]
@allamand No idea unfortunately. I am no longer working on this and have no idea if a solution was ever discovered.

**Comment by hybner** [comment]
@spkane there should be group field. You can try:
```YAML
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: istio-sidecar-injector
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istiod-default-validator
    jqPathExpressions:
    - '.webhooks[]?.failurePolicy'
```
